unit FDM;

interface

uses
  SysUtils, Classes, DB, DBAccess, MyAccess, MemDS, Forms;

type
  TDM = class(TDataModule)
    ConPenjualan: TMyConnection;
    dsqTemp: TMyDataSource;
    dsqListPenjualan: TMyDataSource;
    qListPenjualan: TMyQuery;
    qTemp: TMyQuery;
    dsqInput: TMyDataSource;
    qInput: TMyQuery;
    qInputIdPenjualan: TIntegerField;
    qInputTglPenjualan: TDateField;
    qInputIdKavling: TIntegerField;
    qInputIdHarga: TIntegerField;
    qInputIdMarketing: TIntegerField;
    qInputIdKonsumen: TIntegerField;
    qInputFeeMarketing: TFloatField;
    qInputTenor: TIntegerField;
    qInputHargaJualAJB: TFloatField;
    qInputStatusKPR: TStringField;
    qInputIdJenisPembayaran: TSmallintField;
    qInputNamaBank: TStringField;
    qInputTglAkad: TDateField;
    qInputNoAJB: TStringField;
    qInputInputTime: TDateTimeField;
    qInputOptId: TSmallintField;
    qInputNoBukti: TStringField;
    qInputHargaUnitStd: TFloatField;
    qInputHargaUnit: TFloatField;
    qInputHargaAJB: TFloatField;
    qInputKodeKavling: TStringField;
    qListPenjualanNoBukti: TStringField;
    qListPenjualanNamaKonsumen: TStringField;
    qListPenjualanNoKontak: TStringField;
    qListPenjualanKodeKavling: TStringField;
    qListPenjualanPosisiRumah: TStringField;
    qListPenjualanLuasBangunan: TFloatField;
    qListPenjualanLuasTanahStandar: TFloatField;
    qListPenjualanLuasTanahBPN: TFloatField;
    qListPenjualanKeteranganProgres: TStringField;
    qListPenjualanPersentaseProgres: TFloatField;
    qListPenjualanNIBSplit: TStringField;
    qListPenjualanSHMSplit: TStringField;
    qListPenjualanCaraPembayaran: TStringField;
    qListPenjualanNamaBank: TStringField;
    qListPenjualanStatusKPR: TStringField;
    qListPenjualanTenor: TIntegerField;
    qListPenjualanNamaMarketing: TStringField;
    qListPenjualanHargaJualAJB: TFloatField;
    qListPenjualanFeeMarketing: TFloatField;
    qListPenjualanLuasTanahKelebihan2: TFloatField;
    dsqRefBonus: TMyDataSource;
    qRefBonus: TMyQuery;
    qRefBonusIdBonus: TIntegerField;
    qRefBonusNamaBonus: TStringField;
    qRefBonusBesarBonus: TFloatField;
    qRefBonusInputTime: TDateTimeField;
    qRefBonusOptId: TSmallintField;
    dsqBonus: TMyDataSource;
    qBonus: TMyQuery;
    IntegerField1: TIntegerField;
    StringField1: TStringField;
    FloatField1: TFloatField;
    DateTimeField1: TDateTimeField;
    SmallintField1: TSmallintField;
    qInputTenorThn: TIntegerField;
    qBonusIdPenjualan: TIntegerField;
    qInputDiskon: TFloatField;
    qInputBiayaUpgrade: TFloatField;
    qInputKeteranganUpgrade: TStringField;
    qInputStatusAJB: TSmallintField;
    qListPenjualanIdPenjualan: TIntegerField;
    qInputPajak: TFloatField;
    qInputDiskonStd: TFloatField;
    qInputDiskonTotal: TFloatField;
    qInputPersenHarga: TFloatField;
    dsqLapRekap: TMyDataSource;
    qLapRekap: TMyQuery;
    qLapRekapIdType: TIntegerField;
    qLapRekapNamaType: TStringField;
    qLapRekapJumlahUnit: TLargeintField;
    qLapRekapBookingFee: TLargeintField;
    qLapRekapUangMuka: TLargeintField;
    qLapRekapBlmPjk: TLargeintField;
    qLapRekapReadyStock: TLargeintField;
    qLapRekapSdhLunas: TLargeintField;
    dsqLapDetil: TMyDataSource;
    qLapDetil: TMyQuery;
    qLapDetilKodeKavling: TStringField;
    qLapDetilNoBukti: TStringField;
    qLapDetilTglPenjualan: TDateField;
    qLapDetilJenisPembayaran: TStringField;
    qLapDetilTglPembayaran: TDateField;
    qLapDetilCaraPembayaran: TStringField;
    qLapDetilJumlahPembayaran: TFloatField;
    qInputHargaRumah: TFloatField;
    qInputIncludePajak: TStringField;
    qInputKetGagal: TStringField;
    qListPenjualanStatTransaksi: TStringField;
    dsqLapGagal: TMyDataSource;
    qLapGagal: TMyQuery;
    qLapGagalIdPenjualan: TIntegerField;
    qLapGagalTglPenjualan: TDateField;
    qLapGagalNoBukti: TStringField;
    qLapGagalNamaKonsumen: TStringField;
    qLapGagalNoKontak: TStringField;
    qLapGagalKodeKavling: TStringField;
    qLapGagalPosisiRumah: TStringField;
    qLapGagalPersentaseProgres: TFloatField;
    qLapGagalKetGagal: TStringField;
    qLapGagalCaraPembayaran: TStringField;
    qLapGagalNamaBank: TStringField;
    qLapGagalJenisPembayaran: TStringField;
    qLapGagalJumlahPembayaran: TFloatField;
    qLapGagalStatusKPR: TStringField;
    qLapGagalStatusAJB: TStringField;
    dsqSimulasi: TMyDataSource;
    qSimulasi: TMyQuery;
    qInputNotaris: TStringField;
    qInputBalikNama: TStringField;
    qInputTglBASTR: TDateField;
    qInputTglPDAM: TDateField;
    qInputIdPDAM: TStringField;
    qInputRealisasiPajak: TFloatField;
    qListPenjualanNotaris: TStringField;
    qListPenjualanBalikNama: TStringField;
    qListPenjualanRealisasiPajak: TFloatField;
    qListPenjualanTglBASTR: TDateField;
    qListPenjualanTglPDAM: TDateField;
    qListPenjualanIdPDAM: TStringField;
    dsqLBank: TMyDataSource;
    qLBank: TMyQuery;
    qLBankNamaBank: TStringField;
    dsqLBunga: TMyDataSource;
    qLBunga: TMyQuery;
    qListPenjualanPajak: TFloatField;
    qListPenjualanSelisihPajak: TFloatField;
    qInputSelisihPajak: TFloatField;
    qLBungaSukuBunga: TFloatField;
    dsqLKavUnsold: TMyDataSource;
    qLKavUnsold: TMyQuery;
    qLKavUnsoldIdKavling: TIntegerField;
    qLKavUnsoldIdType: TIntegerField;
    qLKavUnsoldKodeKavling: TStringField;
    qLKavUnsoldPosisiRumah: TStringField;
    qLKavUnsoldNIBSplit: TStringField;
    qLKavUnsoldSHMSplit: TStringField;
    qLKavUnsoldLuasBangunan: TFloatField;
    qLKavUnsoldLuasTanahStandar: TFloatField;
    qLKavUnsoldLuasTanahBPN: TFloatField;
    qLKavUnsoldLebihKurangLuas: TFloatField;
    qLKavUnsoldKeteranganProgres: TStringField;
    qLKavUnsoldPersentaseProgres: TFloatField;
    qLKavUnsoldInputTime: TDateTimeField;
    qLKavUnsoldOptId: TSmallintField;
    qLKavUnsoldHAJBPlan: TFloatField;
    qListPenjualanHargaStd: TFloatField;
    qListPenjualanBiayaUpgrade: TFloatField;
    qListPenjualanHargaUnit: TFloatField;
    dsqLType: TMyDataSource;
    qLType: TMyQuery;
    qLapRekapJmlKavling: TLargeintField;
    qLapRekapRmhContoh: TLargeintField;
    qLapRekapKPRNon: TLargeintField;
    qLapRekapKPRIndent: TLargeintField;
    qLapRekapCashTahapBayar: TLargeintField;
    qLapRekapCashTahapSisa: TLargeintField;
    qLapRekapBASTR: TLargeintField;
    qLapRekapCashKerasBertahap: TLargeintField;
    qLapRekapKPRNonAJB: TLargeintField;
    qLapRekapKPRIndentAJB: TLargeintField;
    dsqLapPenjualan: TMyDataSource;
    qLapPenjualan: TMyQuery;
    qLapPenjualanKodeKavling: TStringField;
    qLapPenjualanNamaKonsumen: TStringField;
    qLapPenjualanTglPenjualan: TDateField;
    qLapPenjualanHargaRumah: TFloatField;
    qLapPenjualanUpgrd: TFloatField;
    qLapPenjualanHargaAllIn: TFloatField;
    qListPenjualanHargaRumah: TFloatField;
    qListPenjualanNamaType: TStringField;
    qListPenjualanNamaProyek: TStringField;
    dsqUnitUnsold: TMyDataSource;
    qUnitUnsold: TMyQuery;
    qUnitUnsoldNamaProyek: TStringField;
    qUnitUnsoldKodeKavling: TStringField;
    qUnitUnsoldLB: TFloatField;
    qUnitUnsoldLT_STD: TFloatField;
    qUnitUnsoldLT_BPN: TFloatField;
    qUnitUnsoldLT_PlusMin: TFloatField;
    qUnitUnsoldPosisiRumah: TStringField;
    qUnitUnsoldPersentaseProgres: TFloatField;
    qUnitUnsoldKeterangan: TStringField;
    qUnitUnsoldHS_Bangunan: TFloatField;
    qUnitUnsoldHS_Tanah: TFloatField;
    qUnitUnsoldHS_Kelebihan: TFloatField;
    qUnitUnsoldH_Std: TFloatField;
    qUnitUnsoldPajak: TFloatField;
    qUnitUnsoldH_Unit: TFloatField;
    qUnitUnsoldNIBSplit: TStringField;
    qUnitUnsoldSHMSplit: TStringField;
    qUnitUnsoldKeteranganProgres: TStringField;
    qUnitUnsoldNamaType: TStringField;
    dsqDetPjk: TMyDataSource;
    qDetPjk: TMyQuery;
    qInputPPn: TFloatField;
    qInputPPh: TFloatField;
    qInputBiayaAJB: TFloatField;
    qInputBiayaLain: TFloatField;
    qListPenjualanRevisiKe: TStringField;
    qUnitUnsoldRevKe: TStringField;
    qLapPenjualanRevisiKe: TStringField;
    qDetPjkvPPNRate: TFloatField;
    qDetPjkvBPHTBRate: TFloatField;
    qDetPjkvPPhRate: TFloatField;
    qDetPjkvBBNRate: TFloatField;
    qListPenjualanTglAkad: TDateField;
    qListPenjualanPPh: TFloatField;
    qInputHargaAllUpgrade: TFloatField;
    qListPenjualanHargaAllUpgrade: TFloatField;
    qDetPjkHAJB: TFloatField;
    qDetPjkPPn: TFloatField;
    qDetPjkBPHTB: TFloatField;
    qDetPjkPPh: TFloatField;
    qDetPjkBAJB: TFloatField;
    qDetPjkBLainPembulatan: TFloatField;
    qDetPjkvPajak: TFloatField;
    qUnitUnsoldSisaAnggaran: TFloatField;
    qListPenjualanNilaiInvestasi: TFloatField;
    qListPenjualanSisaAnggaran: TFloatField;
    qListPenjualanProgPondasi: TFloatField;
    qListPenjualanProgSloof: TFloatField;
    qListPenjualanProgRumah: TFloatField;
    qUnitUnsoldProgPondasi: TFloatField;
    qUnitUnsoldProgSloof: TFloatField;
    qUnitUnsoldProgRumah: TFloatField;
    qInputHrgRumah: TFloatField;
    qLapDetilNamaKonsumen: TStringField;
    qLapDetilStatusPembayaran: TStringField;
    qUnitUnsoldHS_Pelaksanaan: TFloatField;
    qLapPenjualanPajak: TFloatField;
    qLapPenjualanHargaAllUpgrade: TFloatField;
    qUnitUnsoldNilaiInvestasiKavling: TFloatField;
    qUnitUnsoldNilaiInvestasiReady: TFloatField;
    dsqEditUnsold: TMyDataSource;
    qEditUnsold: TMyQuery;
    qEditUnsoldIdHarga: TIntegerField;
    qEditUnsoldNamaProyek: TStringField;
    qEditUnsoldKodeKavling: TStringField;
    qEditUnsoldNamaType: TStringField;
    qEditUnsoldKeteranganProgres: TStringField;
    qEditUnsoldPersentaseProgres: TFloatField;
    qEditUnsoldKeterangan: TStringField;
    qEditUnsoldLB: TFloatField;
    qEditUnsoldLT_STD: TFloatField;
    qEditUnsoldLT_BPN: TFloatField;
    qEditUnsoldLT_PlusMin: TFloatField;
    qEditUnsoldPosisiRumah: TStringField;
    qEditUnsoldHAJB: TFloatField;
    qEditUnsoldPPn: TFloatField;
    qEditUnsoldBPHTB: TFloatField;
    qEditUnsoldPPh: TFloatField;
    qEditUnsoldBAJB: TFloatField;
    qEditUnsoldBLainPembulatan: TFloatField;
    qEditUnsoldPajak: TFloatField;
    qEditUnsoldH_Unit: TFloatField;
    qEditUnsoldNilaiInvestasiKavling: TFloatField;
    qEditUnsoldNilaiInvestasiReady: TFloatField;
    qEditUnsoldSisaAnggaran: TFloatField;
    qEditUnsoldProgPondasi: TFloatField;
    qEditUnsoldProgSloof: TFloatField;
    qEditUnsoldProgRumah: TFloatField;
    qEditUnsoldNIBSplit: TStringField;
    qEditUnsoldSHMSplit: TStringField;
    qEditUnsoldRevKe: TStringField;
    qEditUnsoldHS_Pelaksanaan: TFloatField;
    qEditUnsoldHS_Bangunan: TFloatField;
    qEditUnsoldHS_Tanah: TFloatField;
    qEditUnsoldHS_Kelebihan: TFloatField;
    qEditUnsoldIdType: TIntegerField;
    qUnitUnsoldIdKavling: TIntegerField;
    qUnitUnsoldIdHarga: TIntegerField;
    qUnitUnsoldIdTransaksi: TIntegerField;
    qEditUnsoldIdKavling: TIntegerField;
    qEditUnsoldKetRev: TStringField;
    qUnitUnsoldKetRev: TStringField;
    qEditUnsoldH_Std: TFloatField;
    procedure DataModuleCreate(Sender: TObject);
    procedure ConPenjualanAfterConnect(Sender: TObject);
    procedure CekVersi;
    procedure qInputCalcFields(DataSet: TDataSet);
  private
    { Private declarations }
  public
   vTerminate: Boolean;
   AppName, AppDesc, LastVerStr: String;
   LastVerDate: TDateTime;
   VerNum, LastVer, MustUpdate, VerDate, vLvlOpt: Integer;  
  end;

var
   DM: TDM;

implementation

uses
   DMC;

{$R *.dfm}

procedure TDM.DataModuleCreate(Sender: TObject);
begin
   ConPenjualan.Disconnect;
   AppName := 'Penjualan';
   VerNuM := 128;
   ConPenjualan.Server := FDMC.ConGlobal.Server;
   ConPenjualan.Database := FDMC.ConGlobal.Database;
   ConPenjualan.Username := FDMC.ConGlobal.Username;
   ConPenjualan.Password := FDMC.ConGlobal.Password;
   ConPenjualan.Port := FDMC.ConGlobal.Port;
   ConPenjualan.Connect;
end;

procedure TDM.ConPenjualanAfterConnect(Sender: TObject);
begin
   vTerminate := False;
   VerDate := FileAge(Application.ExeName);
   CekVersi;
end;

procedure TDM.CekVersi;
begin
   with qTemp do
   begin
      Close;
      SQL.Clear;
      SQL.Add('SELECT * FROM appversion WHERE AppName = '''+AppName+'''');
      Open;
   end;        
   AppDesc    := qTemp.FieldByName('AppDesc').AsString;
   LastVer    := qTemp.FieldByName('LastVer').AsInteger;
   LastVerStr := qTemp.FieldByName('LastVerStr').AsString;

   if (LastVer > VerNum) or (FileDateToDateTime(VerDate) < qTemp.FieldByName('LastVerDate').AsDateTime)
   then MustUpdate := 1 else MustUpdate := 0;
end;

procedure TDM.qInputCalcFields(DataSet: TDataSet);
begin
   qInput.FieldByName('SelisihPajak').AsFloat := qInput.FieldByName('Pajak').AsFloat -
                                                 qInput.FieldByName('RealisasiPajak').AsFloat;
end;

end.
